name: Docker Build

on:
  push:
    branches:
      - legacy
      - 'build/**'      
  pull_request:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:

  changelog:
    name: Changelog
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      tag: ${{ steps.changelog.outputs.tag }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy Image
    needs: [changelog]
    if: github.event_name != 'pull_request' && needs.changelog.outputs.skipped == 'false'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: docker.io
      IMAGE_NAME: firezone  

    steps:

      - uses: actions/checkout@v7.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get repository name
        id: get_repo
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract version parts
        id: extract_version
        run: |
          VERSION=${{ needs.changelog.outputs.version }}
          MAJOR_MINOR=$(echo $VERSION | cut -d'.' -f1,2)
          echo "MAJOR_MINOR_TAG=${MAJOR_MINOR}.x" >> $GITHUB_ENV

      - name: Setup Docker Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}
          tags: |
            latest
            ${{ needs.changelog.outputs.version }}
            ${{ env.MAJOR_MINOR_TAG }}            

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          file: Dockerfile.prod
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
              VERSION=${{ needs.changelog.outputs.version }}

  deploy-arm:
    name: Deploy ARM Image
    needs: [changelog, deploy]
    if: github.event_name != 'pull_request' && needs.changelog.outputs.skipped == 'false'
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: docker.io
      IMAGE_NAME: firezone  

    steps:

      - uses: actions/checkout@v7.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get repository name
        id: get_repo
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract version parts
        id: extract_version
        run: |
          VERSION=${{ needs.changelog.outputs.version }}
          MAJOR_MINOR=$(echo $VERSION | cut -d'.' -f1,2)
          echo "MAJOR_MINOR_TAG=${MAJOR_MINOR}.x" >> $GITHUB_ENV

      - name: Setup Docker Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}
          tags: |
            latest-arm64
            ${{ needs.changelog.outputs.version }}-arm64
            ${{ env.MAJOR_MINOR_TAG }}-arm64

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64
          file: Dockerfile.prod
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
              VERSION=${{ needs.changelog.outputs.version }}
  
  release:
    name: Release
    needs: [changelog, deploy]
    if: github.event_name != 'pull_request' && needs.changelog.outputs.skipped == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
  
      - name: Debug Changelog Outputs
        run: echo ${{ needs.changelog.outputs.tag }}
        
      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.changelog.outputs.tag }}
          prerelease: false
          draft: false
          generate_release_notes: true
          name: ${{ needs.changelog.outputs.tag }}
          body: |
            <details>
              <summary>🤖 Autogenerated Conventional Changelog</summary>
  
            ${{ needs.changelog.outputs.clean_changelog }}
            </details>
